// Auto-generated by generate-sites-manifest.py
// Generated: 2026-06-25T17:00:08Z
const SITES = [
  { id:1, name:'Demon Lord', url:'https://demon-lord-guide.vercel.app', steam:3720420, pages:11, style:'B-暗黑史诗', styleTag:'style-b', feats:{adsense:1,adstxt:1,afdian:1,ga4:1,gsc:1}, push:'', update:'', eng:0, pps:0, launch:'6/25', draft:false },
  { id:2, name:'Dispatch', url:'https://dispatch-guide-sigma.vercel.app', steam:2592160, pages:14, style:'A-战术指挥', styleTag:'style-a', feats:{adsense:1,adstxt:1,afdian:1,ga4:1,gsc:1}, push:'', update:'', eng:0, pps:0, launch:'6/23', draft:false },
  { id:3, name:'Game-Station.Zip', url:'https://game-guide-station.zip.vercel.app', steam:0, pages:0, style:'未知', styleTag:'style-a', feats:{adsense:1,adstxt:1,afdian:1,ga4:1,gsc:1}, push:'', update:'', eng:0, pps:0, launch:'?', draft:true },
  { id:4, name:'Going Medieval', url:'https://going-medieval-guide.vercel.app', steam:1029780, pages:53, style:'3-古卷羊皮纸', styleTag:'style-3', feats:{adsense:1,adstxt:1,afdian:1,ga4:1,gsc:1}, push:'', update:'', eng:0, pps:0, launch:'6/25', draft:false },
  { id:5, name:'MENACE', url:'https://menace-guide.vercel.app', steam:2432860, pages:18, style:'A-战术指挥', styleTag:'style-a', feats:{adsense:1,adstxt:1,afdian:1,ga4:1,gsc:1}, push:'', update:'', eng:0, pps:0, launch:'6/23', draft:false },
  { id:6, name:'Olden Era', url:'https://olden-era-guide-tau.vercel.app', steam:3105440, pages:18, style:'B-暗黑史诗', styleTag:'style-b', feats:{adsense:1,adstxt:1,afdian:1,ga4:1,gsc:1}, push:'', update:'', eng:0, pps:0, launch:'6/25', draft:false },
  { id:7, name:'Solarpunk', url:'https://solarpunk-game-wiki.vercel.app', steam:1805110, pages:20, style:'C-生存日志', styleTag:'style-c', feats:{adsense:1,adstxt:1,afdian:1,ga4:1,gsc:1}, push:'', update:'', eng:0, pps:0, launch:'6/23', draft:false },
  { id:8, name:'Tabletop Tavern', url:'https://tabletop-tavern-guide.vercel.app', steam:3337380, pages:16, style:'A-战术指挥', styleTag:'style-a', feats:{adsense:1,adstxt:1,afdian:1,ga4:1,gsc:1}, push:'', update:'', eng:0, pps:0, launch:'6/25', draft:false },
  { id:9, name:'Town to City', url:'https://town-to-city-guide.vercel.app', steam:0, pages:15, style:'A-战术指挥', styleTag:'style-a', feats:{adsense:1,adstxt:1,afdian:1,ga4:1,gsc:1}, push:'', update:'', eng:0, pps:0, launch:'6/25', draft:true },
];